#!/usr/bin/env python3
# Regenerate recipes-arduino/arduino-zephyr-core/{files/*_index.json,srcuri.inc}.
#
# On the board, install the core into a scratch arduino-cli data dir, keeping
# the downloaded archives:
#   printf 'directories:\n  data: /var/tmp/ac/data\n  downloads: /var/tmp/ac/staging\n  user: /var/tmp/ac/user\n' > cli.yaml
#   arduino-cli --config-file cli.yaml core update-index
#   arduino-cli --config-file cli.yaml core install arduino:zephyr@<version>
# then copy back data/package_index.json, data/library_index.json and the list
# of archive file names in staging/, and run:
#   arduino-core-seed.py package_index.json library_index.json archives.txt libraries.txt <recipe dir>
# libraries.txt lists "Name@version", one per line: the libraries pinned by
# the example apps' sketch profiles (and the platform's library dependencies),
# which arduino-cli installs at compile time. The indexes are trimmed to these
# entries (arduino-cli installs offline from them and the archives).
import json, re, sys

pkg_path, lib_path, list_path, libs_path, out = sys.argv[1:6]
pkg = json.load(open(pkg_path))
lib = json.load(open(lib_path))
files = {l.strip().split("/")[-1] for l in open(list_path) if l.strip()}

ents = []
trimmed = {"packages": []}
for p in pkg["packages"]:
    q = {k: v for k, v in p.items() if k not in ("platforms", "tools")}
    q["platforms"] = [pl for pl in p.get("platforms", []) if pl["archiveFileName"] in files]
    q["tools"] = []
    for t in p.get("tools", []):
        systems = [s for s in t.get("systems", []) if s["archiveFileName"] in files]
        if systems:
            q["tools"].append(dict(t, systems=systems))
    for pl in q["platforms"]:
        ents.append(("packages", pl["url"], pl["archiveFileName"], pl["checksum"]))
    for t in q["tools"]:
        for s in t["systems"]:
            ents.append(("packages", s["url"], s["archiveFileName"], s["checksum"]))
    if q["platforms"] or q["tools"]:
        trimmed["packages"].append(q)
wanted = {l.strip() for l in open(libs_path) if l.strip() and not l.startswith("#")}
libs = [l for l in lib["libraries"]
        if l["archiveFileName"] in files or "%s@%s" % (l["name"], l["version"]) in wanted]
unknown = wanted - {"%s@%s" % (l["name"], l["version"]) for l in libs}
if unknown:
    sys.exit("libraries not in the index: %s" % " ".join(sorted(unknown)))
for l in libs:
    ents.append(("libraries", l["url"], l["archiveFileName"], l["checksum"]))

missing = files - {e[2] for e in ents}
files |= {e[2] for e in ents}
if missing:
    sys.exit("not in the indexes: %s" % " ".join(sorted(missing)))

json.dump(trimmed, open(out + "/files/package_index.json", "w"), indent=1)
json.dump({"libraries": libs}, open(out + "/files/library_index.json", "w"), indent=1)

lines, sums = [], []
for kind, url, fn, ck in sorted(ents, key=lambda e: e[2]):
    name = re.sub(r"[^A-Za-z0-9]", "-", fn)
    lines.append("    %s;name=%s;downloadfilename=%s;unpack=0;subdir=staging/%s \\" % (url, name, fn, kind))
    sums.append('SRC_URI[%s.sha256sum] = "%s"' % (name, ck.split(":")[1]))
with open(out + "/srcuri.inc", "w") as f:
    f.write("# Generated by scripts/arduino-core-seed.py: the archives arduino-cli\n"
            "# downloads to install the core on aarch64.\n")
    f.write('SRC_URI += " \\\n' + "\n".join(lines) + '\n"\n\n' + "\n".join(sums) + "\n")
print("%d archives" % len(ents))
